matrix:
- name: ReST
  aspell:
    lang: ru
    ignore-case: true
  dictionary:
    wordlists:
    - config/spellcheck/.wordlist.txt
    - config/spellcheck/.wordlist_en.txt
    encoding: utf-8
    output: build/dictionary/dictionary.dic
  pipeline:
  - resplendent.filters.restructuredtext:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - :matches(code, pre)
  sources:
  - 'lab*/*.rst'
  - 'docs/**/*_ru.rst'
  default_encoding: utf-8
